const SET_Q_NUMBER = "SET_Q_NUMBER";
const GET_RANDOM_QUESTION = "GET_RANDOM_QUESTION";
const SET_ANSWERS = "SET_ANSWERS";
const HIDE_5050 = "HIDE_5050";
const SHOW_5050 = "SHOW_5050";
const HIDE_REVIEW = "HIDE_REVIEW";
const SHOW_REVIEW = "SHOW_REVIEW";
const SHOW_REVIEW_MODAL = "SHOW_REVIEW_MODAL";
const CLOSE_REVIEW_MODAL = "CLOSE_REVIEW_MODAL";
const SHOW_GG = "SHOW_GG";
const HIDE_GG = "HIDE_GG";
const HIDE_ASK = "HIDE_ASK";
const SHOW_ASK = "SHOW_ASK";
const SHOW_ASK_MODAL = "SHOW_ASK_MODAL";
const CLOSE_ASK_MODAL = "CLOSE_ASK_MODAL";
const SHOW_PRO_MODAL = "SHOW_PRO_MODAL";
const CLOSE_PRO_MODAL = "CLOSE_PRO_MODAL";
const SET_IMG_ASK = "SET_IMG_ASK";
const SET_ASK_STATE = "SET_ASK_STATE";
const SHOW_CORRECT_MODAL = "SHOW_CORRECT_MODAL";
const CLOSE_CORRECT_MODAL = "CLOSE_CORRECT_MODAL";
const SHOW_WRONG_MODAL = "SHOW_WRONG_MODAL";
const CLOSE_WRONG_MODAL = "CLOSE_WRONG_MODAL";
const SHOW_STOP_PLAY_MODAL = "SHOW_STOP_PLAY_MODAL";
const CLOSE_STOP_PLAY_MODAL = "CLOSE_STOP_PLAY_MODAL";
const SHOW_CLICK_STOP_MODAL = "SHOW_CLICK_STOP_MODAL";
const CLOSE_CLICK_STOP_MODAL = "CLOSE_CLICK_STOP_MODAL";
export {
  SET_Q_NUMBER,
  GET_RANDOM_QUESTION,
  SET_ANSWERS,
  HIDE_5050,
  SHOW_5050,
  HIDE_ASK,
  SHOW_ASK,
  HIDE_GG,
  SHOW_GG,
  HIDE_REVIEW,
  SHOW_REVIEW,
  SHOW_ASK_MODAL,
  CLOSE_ASK_MODAL,
  SHOW_REVIEW_MODAL,
  CLOSE_REVIEW_MODAL,
  CLOSE_PRO_MODAL,
  SHOW_PRO_MODAL,
  SET_ASK_STATE,
  SET_IMG_ASK,
  SHOW_CORRECT_MODAL,
  CLOSE_CORRECT_MODAL,
  SHOW_WRONG_MODAL,
  CLOSE_WRONG_MODAL,
  SHOW_STOP_PLAY_MODAL,
  CLOSE_STOP_PLAY_MODAL,
  SHOW_CLICK_STOP_MODAL,
  CLOSE_CLICK_STOP_MODAL,
};
