const GET_CATEGORIES = "GET_CATEGORIES";
const GET_STORIES = "GET_STORIES";
const GET_AUTHORS = "GET_AUTHORS";
const SET_STORIES_AWAIT = "SET_STORY_AWAIT";
const SET_SEARCH = "SET_SEARCH";
export {
  GET_CATEGORIES,
  GET_STORIES,
  SET_STORIES_AWAIT,
  GET_AUTHORS,
  SET_SEARCH,
};
