"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var CanBo_1 = require("./CanBo");
var CongNhan_1 = require("./CongNhan");
var Gender_1 = require("./Gender");
var KySu_1 = require("./KySu");
var NhanVien_1 = require("./NhanVien");
var QLCB_1 = require("./QLCB");
var congNhan1 = new CongNhan_1.CongNhan("Nguyen Vat Va", 30, Gender_1.Gender.NAM, "Hẻm Làm Thuê", 1);
var congNhan2 = new CongNhan_1.CongNhan("Tran Cham Chi", 18, Gender_1.Gender.NAM, "Xóm Cần Cù", 7);
var kySu1 = new KySu_1.KySu("Le Trinh Do", 25, Gender_1.Gender.KHAC, "Đại lộ Lighting", "Cầu Cống");
var nhanVien1 = new NhanVien_1.NhanVien("Do Cu Ly", 29, Gender_1.Gender.NU, "Hẻm Làm Thuê", "Lao Công");
var nhanVien2 = new NhanVien_1.NhanVien("Ly Thi Buon", 21, Gender_1.Gender.NU, "Xóm Ồn Ào", "Lễ Tân");
CanBo_1.CanBo.canBos.push(congNhan1);
CanBo_1.CanBo.canBos.push(congNhan2);
CanBo_1.CanBo.canBos.push(kySu1);
CanBo_1.CanBo.canBos.push(nhanVien1);
CanBo_1.CanBo.canBos.push(nhanVien2);
console.log(CanBo_1.CanBo.canBos);
QLCB_1.QLCB.menu();
