const GET_ALL_COMPETITIONS = "GET_ALL_COMPETITIONS";
const GET_ALL_TEAMS = "GET_ALL_TEAMS";
const GET_TEAM_BY_COMPETITION = "GET_TEAM_BY_COMPETITION";
const GET_ALL_PLAYERS = "GET_ALL_PLAYERS";
const GET_PLAYERS_BY_TEAM = "GET_PLAYERS_BY_TEAM";
const SHOW_DELETE_TEAMS_FORM = "SHOW_DELETE_TEAMS_FORM";
const CLOSE_DELETE_TEAMS_FORM = "CLOSE_DELETE_TEAMS_FORM";
const SHOW_TEAMINFO = "SHOW_TEAMINFO";
const CLOSE_TEAMINFO = "CLOSE_TEAMINFO";
const SHOW_ADD_TEAM = "SHOW_ADD_TEAM";
const CLOSE_ADD_TEAM = "CLOSE_ADD_TEAM";
const SHOW_SINGLE_DELETE_TEAM = "SHOW_SINGLE_DELETE_TEAM";
const CLOSE_SINGLE_DELETE_TEAM = "CLOSE_SINGLE_DELETE_TEAM";
const SHOW_ADD_PLAYER = "SHOW_ADD_PLAYER";
const CLOSE_ADD_PLAYER = "CLOSE_ADD_PLAYER";
const SHOW_EDIT_PLAYER = "SHOW_EDIT_PLAYER";
const CLOSE_EDIT_PLAYER = "CLOSE_EDIT_PLAYER";
const SHOW_DELETE_PLAYERS = "SHOW_DELETE_PLAYERS";
const CLOSE_DELETE_PLAYERS = "CLOSE_DELETE_PLAYERS";
const SHOW_SINGLE_DELETE_PLAYER = "SHOW_SINGLE_DELETE_PLAYER";
const CLOSE_SINGLE_DELETE_PLAYER = "CLOSE_SINGLE_DELETE_PLAYER";
const SET_PLAYER_EDIT = "SET_PLAYER_EDIT";

export {
  GET_ALL_COMPETITIONS,
  GET_ALL_TEAMS,
  GET_TEAM_BY_COMPETITION,
  GET_ALL_PLAYERS,
  GET_PLAYERS_BY_TEAM,
  SHOW_DELETE_TEAMS_FORM,
  CLOSE_DELETE_TEAMS_FORM,
  SHOW_TEAMINFO,
  CLOSE_TEAMINFO,
  SHOW_ADD_TEAM,
  CLOSE_ADD_TEAM,
  SHOW_SINGLE_DELETE_TEAM,
  CLOSE_SINGLE_DELETE_TEAM,
  SHOW_ADD_PLAYER,
  CLOSE_ADD_PLAYER,
  SHOW_DELETE_PLAYERS,
  CLOSE_DELETE_PLAYERS,
  SHOW_EDIT_PLAYER,
  CLOSE_EDIT_PLAYER,
  SHOW_SINGLE_DELETE_PLAYER,
  CLOSE_SINGLE_DELETE_PLAYER,
  SET_PLAYER_EDIT,
};
